### ISSUE TITLE
README.md contain unused/wrong description 

### ISSUE THREAD

**Issue by New-az** [KorawitRupanya/Project-OSWA#11]
1. Documents 
Trello board : [Trello/back-end](https://trello.com/b/TtDLhCaC) not found.
If you didn't used this board then remove.

2. Installation instructions.
Actually ```npm start``` run with localhost:3000 on my browser

**Comment by KameriiJ** [comment]
Thanks!! I read the localhost number wrong ; _ ;. I'll fix it. About Trello/back-end, I'll tell my friend to check trello board permission.
